In [1]:
import numpy as np
arr = np.arange (2,50,3)
print ("printing a numpy array from 2 to 50 with a stepsize of 3\n " ,arr )

printing a numpy array from 2 to 50 with a stepsize of 3
  [ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47]


In [31]:
list = [] # blank list no 1
for i in range (0,5):
    num = int (input (" Enter 5 Elements No : "))
    list.append(num)
    
list1 = [] # blank list no 2
for i in range (0,5):
    num1 = int (input (" Enter 5 Elements No : "))
    list1.append(num1)
    

#Importing Numpy 
import numpy as np 
#Converting List To Numpy Arrays
arr = np.array(list)
arr1 = np.array(list1)
#printing first list 
print ("List : ", list)
#priting array 
print ("Array :", arr)
#printing second list 
print ("List : ",list1)
#printing array
print ("Array :" , arr1)



 Enter 5 Elements No : 20
 Enter 5 Elements No : 34
 Enter 5 Elements No : 12
 Enter 5 Elements No : 3
 Enter 5 Elements No : 4
 Enter 5 Elements No : 12
 Enter 5 Elements No : 54
 Enter 5 Elements No : 13
 Enter 5 Elements No : 2
 Enter 5 Elements No : 1
List :  [20, 34, 12, 3, 4]
Array : [20 34 12  3  4]
List :  [12, 54, 13, 2, 1]
Array : [12 54 13  2  1]


In [32]:
#Concatenation of arrays
con = np.concatenate((arr,arr1))
print("Concatenation : " ,con)

Concatenation :  [20 34 12  3  4 12 54 13  2  1]


In [33]:
#Sorting of arrays
print (np.sort(arr))
print (np.sort(arr1))

[ 3  4 12 20 34]
[ 1  2 12 13 54]


In [10]:
#creating a numpy array
arr = np.array ([[1,2,3],[9,8,7]])
print ("type of array :" , type (arr))
print ("no of dimensions :", arr.ndim)
print ("size of array : ", arr.size)

type of array : <class 'numpy.ndarray'>
no of dimensions : 2
size of array :  6


In [24]:
#creating a single array
arr = np.array([1,4,6])
print (arr.shape)
print ("type of array :", arr.ndim)
#coverting 1d array into 2d array
print ("Converting 1D array to 2D array \n")
arr = arr [:, np.newaxis]
print(arr.shape)
print ("type of array :" ,arr.ndim)

(3,)
type of array : 1
Converting 1D array to 2D array 

(3, 1)
type of array : 2


In [3]:
import numpy as np
#Creating 2 square numpy arrays 
a =np.array ([[12, 14],[34, 56]])
b=np.array ([[65, 23], [20,31]])
# vertical stacking 
print("Vertical stacking:\n", np.vstack((a, b))) 
  
# horizontal stacking 
print("\nHorizontal stacking:\n", np.hstack((a, b))) 

Vertical stacking:
 [[12 14]
 [34 56]
 [65 23]
 [20 31]]

Horizontal stacking:
 [[12 14 65 23]
 [34 56 20 31]]


In [21]:
#Getting unique items from a list
list = [1,1,2,3,4,4,5,6,7,7,8,9]
un_list =[]
for a in list:
    if a not in un_list:
         un_list.append(a)
print ("\n Unique no in list : \n", un_list)

#taking input list for count
l1=[]
count = 0
for i in list:
    if i not in l1:
        count +=1
        l1.append(i)
        
print ("\n No of unique items :",count)



 Unique no in list : 
 [1, 2, 3, 4, 5, 6, 7, 8, 9]

 No of unique items : 9
